-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.material
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    price_per_unit integer NOT NULL,
    unit character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Consumation"
(
    id integer NOT NULL,
    product1_id integer NOT NULL,
    material_id integer NOT NULL,
    quatity integer NOT NULL,
    consumation_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Consumation"
    ADD FOREIGN KEY (consumation_id)
    REFERENCES public.material (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Consumation"
    ADD FOREIGN KEY (product1_id)
    REFERENCES public."Product" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;